name: release
run-name: release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+" # v1.0.0
    branches: [main]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - .gitignore
      - .github/**

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout code

      - shell: pwsh # install dependencies
        run: .\Build\build.ps1 -ResolveDependency -TaskList 'Init'

      - shell: pwsh # stage module
        run: .\Build\build.ps1 -TaskList 'CombineFunctionsAndStage'

      - shell: pwsh # psscriptanalyzer
        run: .\Build\build.ps1 -TaskList 'Analyze'

      - shell: pwsh # pester
        run: .\Build\build.ps1 -TaskList 'Test'

      - shell: pwsh # build documentation
        run: .\Build\build.ps1 -TaskList 'UpdateDocumentation'

      - shell: pwsh # compress module
        run: .\Build\build.ps1 -TaskList 'CreateBuildArtifact'

      - uses: actions/upload-artifact@v6 # publish compressed module
        with:
          name: Artifacts
          path: "Artifacts"
          if-no-files-found: error

      - uses: softprops/action-gh-release@v2 # release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: Artifacts/*.zip
